anke/urls.py
from django.urls import path
from anke import views

app_name='anke'
urlpatterns = [
    path('', views.index, name='index'),
    path('anke/', views.ankeView, name='anke'),
    path('list/', views.ankeList, name='list'),
    path('export/', views.ankeExport, name='export'),
    path('table/', views.tableView, name='table'),
    path('success/', views.successView, name='success'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anke.urls')),
      # User management
    path('accounts/', include('allauth.urls')), # new
]

anke/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.core.mail import EmailMessage
from django.template.loader import render_to_string


class Traffic(models.Model):
    name = models.CharField(max_length=255, verbose_name=('交通手段'))
    slug = models.SlugField(unique=True, verbose_name=('スラグ'))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=('作成日時'))

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = ('質問３（交通手段）')
        verbose_name_plural = ('質問３（交通手段）')


class Person(models.Model):
    name = models.CharField(max_length=255, verbose_name=('同伴者'))
    slug = models.SlugField(unique=True, verbose_name=('スラグ'))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=('作成日時'))

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = ('質問４（人物）')
        verbose_name_plural = ('質問４（人物）')


class Purpose(models.Model):
    name = models.CharField(max_length=255, verbose_name=('目的'))
    slug = models.SlugField(unique=True, verbose_name=('スラグ'))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=('作成日時'))

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = ('質問５（目的）')
        verbose_name_plural = ('質問５（目的）')


class Media(models.Model):
    name = models.CharField(max_length=255, verbose_name=('メディア種別'))
    slug = models.SlugField(unique=True, verbose_name=('スラグ'))
    timestamp = models.DateTimeField(auto_now_add=True, verbose_name=('作成日時'))

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = ('質問６（メディア）')
        verbose_name_plural = ('質問６（メディア）')


class Anke(models.Model):
    
    STATUS_CHOICES = (
        ('on', 'オンライン'),
        ('off', '紙'),
    )

    VISIT_CHOICES = (
        ('0', '初めて'),
        ('1', '２回目〜５回目'),
        ('2', '６回目〜１０回目'),
        ('3', '１０回以上'),
        ('4', '地元住民'),
    )
    
    AGE_CHOICES = (
        ('0', '20歳未満'),
        ('1', '20歳以上〜30歳未満'),
        ('2', '30歳以上〜40歳未満'),
        ('3', '40歳以上〜50歳未満'),
        ('4', '50歳以上〜60歳未満'),
        ('6', '60歳以上〜70歳未満'),
        ('7', '70歳以上'),
    )
    
    MONEY_CHOICES = (
        ('0', '1000円未満'),
        ('1', '1000円以上〜2000円未満'),
        ('2', '2000円以上〜3000円未満'),
        ('3', '4000円以上〜5000円未満'),
        ('4', '5000円以上〜10000円未満'),
        ('5', '10000円以上'),
    )

    SHOP_CHOICES = (
        ('ka', 'カパテリア'),
        ('be', '紅乙女酒造'),
        ('ky', '巨峰ワイン'),
        ('ju', '樹蘭マルシェ'),
        ('others', 'その他'),
    )

    GENDER_CHOICES = (
        ('m', '男性'),
        ('f', '女性'),
        ('c', 'カスタム'),
    )

    name = models.CharField(max_length=200, verbose_name=('氏名'))
    shop = models.CharField(max_length=300, default='others', verbose_name=('お店'), choices=SHOP_CHOICES)
    age = models.CharField(max_length=200, null=True, verbose_name=('年代'), blank=True,  choices=AGE_CHOICES)
    gender = models.CharField(max_length=200, verbose_name=('性別'), choices=GENDER_CHOICES, null=True, blank=True)
    address = models.CharField(blank=True, null=True, max_length=300, verbose_name=('住所'))
    email = models.EmailField(verbose_name=('Eメールアドレス'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=('回答日時'), null=True)
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, verbose_name='回答手段', null=True, default='on')
    question1 = models.CharField(max_length=300, blank=True, choices=VISIT_CHOICES, default='0', verbose_name=('質問1'))
    question2 = models.CharField(max_length=300, blank=True, null=True, verbose_name=('質問2'))
    question3 = models.ForeignKey(Traffic, on_delete=models.PROTECT, verbose_name='質問3', blank=True, null=True)
    question4 = models.ManyToManyField(Person, verbose_name='質問4', blank=True)
    question5 = models.ManyToManyField(Purpose, verbose_name='質問5', blank=True)
    question6 = models.ManyToManyField(Media, verbose_name='質問6', blank=True)
    question7 = models.CharField(max_length=300, blank=True, null=True, verbose_name=('質問7'))
    question8 = models.CharField(max_length=300, blank=True, choices=MONEY_CHOICES, default='0', verbose_name=('質問8'))
    question9 = models.CharField(max_length=300, blank=True, choices=MONEY_CHOICES, default='0', verbose_name=('質問9'))
    question10 = models.CharField(max_length=300, blank=True, null=True, verbose_name=('質問10'))
    question11 = models.TextField(blank=True, null=True, verbose_name=('質問11'))
    question12 = models.CharField(max_length=300, blank=True, null=True, verbose_name=('質問12'))
    question13 = models.PositiveIntegerField(blank=True, null=True, verbose_name=('質問13'))
    question14 = models.TextField(blank=True, null=True, verbose_name=('質問14'))
    question15 = models.TextField(blank=True, null=True, verbose_name=('質問15'))
    notification = models.BooleanField(default=False, null=True, verbose_name=('メルマガ'))

    class Meta:
        ordering = ['-created']
        verbose_name = ('アンケート')
        verbose_name_plural = ('アンケート')

    def __str__(self):
        return self.name

    
class Newsletter(models.Model):
    title = models.CharField(max_length=300, null=True, verbose_name=('タイトル'))
    message = models.TextField(verbose_name=('本文'))
    created = models.DateTimeField(auto_now_add=True, verbose_name=('作成日時'), null=True)

    class Meta:
        ordering = ['-created']
        verbose_name = ('メールマガジン')
        verbose_name_plural = ('メールマガジン')

    def __str__(self):
        return self.title

    def email_push(self, request):
        context = {
            'news': self,
        }
        subject = render_to_string('anke/notify_subject.txt', context, request)
        message = render_to_string('anke/notify_message.txt', context, request)

        from_email = settings.DEFAULT_FROM_EMAIL
        bcc = [settings.DEFAULT_FROM_EMAIL]
        for mail_push in Anke.objects.filter(notification=True):
            bcc.append(mail_push.email)
        email = EmailMessage(subject, message, from_email, [], bcc)
        email.send()

anke/forms.py
from django.forms import *
from anke.models import *


class AnkeForm(ModelForm):

    class Meta:
        model = Anke
        fields = ('name', 'shop', 'gender', 'age', 'address', 'email', 'question1', 'question2', 'question3', 'question4', 'question5', 'question6', 'question7', 'question8', 'question9', 'question10', 'question11', 'question12', 'question13', 'question14', 'question15', 'notification')
        question3 = ModelChoiceField(queryset=Traffic.objects.all())
        question4 = ModelMultipleChoiceField(queryset=Person.objects.all())
        question5 = ModelMultipleChoiceField(queryset=Purpose.objects.all())
        question6 = ModelMultipleChoiceField(queryset=Media.objects.all())
        widgets = {
            'name': TextInput(attrs={
                'placeholder': 'フルネームで記入して下さい',
            }),
            'shop': Select(attrs={
                'placeholder': '選択して下さい',
            }),
            'gender': Select(attrs={
                'placeholder': '選択して下さい',
            }),
            'age': Select(attrs={
                'placeholder': '数字を記入して下さい',
            }),
            'address': TextInput(attrs={
                'placeholder': '市町村名までで結構です',
            }),
            'email': EmailInput(attrs={
                'placeholder': '普段ご利用のEメールアドレスをご入力ください',
            }),
            'question1': Select(attrs={
                'placeholder': '数字を入力してください。',
            }),
            'question2': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'question3': Select(attrs={
                'placeholder': '選択してください',
            }),
            'question4': CheckboxSelectMultiple(attrs={
                'placeholder': '選択してください',
            }),
            'question5': CheckboxSelectMultiple(attrs={
                'placeholder': '選択してください',
            }),
            'question6': CheckboxSelectMultiple(attrs={
                'placeholder': '選択してください',
            }),
            'question7': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'question8': Select(attrs={
                'placeholder': '金額の数字を入力してください',
            }),
            'question9': Select(attrs={
                'placeholder': '金額の数字を入力してください',
            }),
            'question10': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'question11': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'question12': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'question13': NumberInput(attrs={
                'placeholder': '数字を入力してください',
            }),
            'question14': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'question15': TextInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
            'notification': CheckboxInput(attrs={
                'placeholder': '自由に記入して下さい',
            }),
        }
        labels = {
            'name': 'お名前',
            'shop': 'ご来店の店舗名',
            'gender': '性別',
            'age': 'ご年代',
            'address': 'ご住所',
            'email': 'Eメールアドレス',
            'question1': '質問1：耳納北麓エリアに来るのは何回目ですか？',
            'question2': '質問2：このエリアに来る前に、比較した場所があったら教えてください。',
            'question3': '質問3：本日の移動手段は？',
            'question4': '質問4：本日は、どなたとご一緒ですか？(複数選択可)。',
            'question5': '質問5：本日の主な目的は？(複数選択可)。',
            'question6': '質問6：何をご覧になって来られましたか？(複数選択可)',
            'question7': '質問7：この後耳納北麓エリア以外に訪れる予定の場所があれば、ご記入ください。',
            'question8': '質問8：耳納北麓エリアで食事に使う費用はいくらですか？',
            'question9': '質問9：耳納北麓エリアで土産など買い物に使う費用はいくらですか？',
            'question10': '質問10：耳納北麓エリアで一番好きなところは？（例：施設、お店、風景など）',
            'question11': '質問11：このエリアに来ると決めた理由は何ですか？',
            'question12': '質問12：今まで旅行した中で、一番好きだった場所はどこですか？',
            'question13': '質問13：その場所が100点とすると、このエリアは何点ですか？',
            'question14': '質問14：その点数にした（減点した）理由は何ですか？',
            'question15': '質問15：このエリアに欠けてるものがあるとすれば、それは何でしょうか？',
            'notification': '<span class="text-success lead">久留米ＤＭＯメルマガ登録</span><br>ご希望の方は左上のボックスをタップして<br><span class="text-primary">チェック</span>を付けてください。',
        }

anke/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.mail import send_mail, send_mass_mail, BadHeaderError
from anke.models import Anke
from anke.forms import AnkeForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required

import csv
import io
import urllib

def index(request):
    return render(request, "anke/index.html")

def ankeView(request):
    params ={'message': '', 'form': None}
    if request.method == 'POST':
        form = AnkeForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            from_email = form.cleaned_data['email']
            message1 = (f"アンケート回答のお知らせ。「{name}」さま", f"「{name}」さまがアンケートに回答されました。", from_email, ['s-shotaro@berraquera-jp.com'])
            message2 = ("アンケート回答のお礼", f"「{name}」 さま \n ご回答ありがとうございます。\n\nJR田主丸駅構内のカフェ「カパテリア」で「400円分サービス」させていただきます。 \n\nご利用の際はスタッフにこのメールをお見せください。\n\n※メルマガにご登録の方は、今後の配信をお待ちください。", from_email, [from_email])
            try:
                send_mass_mail((message1, message2), fail_silently=False)
            except BadHeaderError:
                return HttpResponse('無効なヘッダーが見つかりました。')
            survey = form.save(commit=False)
            survey = form.save()
            form.save_m2m()
            return redirect('anke:success')
        else:
            params['message'] = '再入力して下さい'
            params['form'] = form
    else:
        params['form'] = AnkeForm()
    return render(request, 'anke/survey.html', params)


@staff_member_required
@login_required
def ankeList(request):
    data = Anke.objects.all()
    return render(request, 'anke/list.html', {'data': data})


@staff_member_required
def ankeExport(request):
    data = Anke.objects.all()
    response = HttpResponse(content_type='text/csv; charset=Shift-JIS')
    filename = urllib.parse.quote((u'アンケート回答リスト.csv').encode("utf8"))
    response['Content-Disposition'] = 'attachment; filename*=UTF-8\'\'{}'.format(filename)
    writer = csv.writer(response)
    writer.writerow(['回答日', '手段', '氏名', '住所', '年代', '性別', 'メルマガ', 'Eメールアドレス', '質問１', '質問２', '質問３', '質問４', '質問５', '質問６', '質問7', '質問8', '質問9', '質問10', '質問11', '質問12', '質問13', '質問14', '質問15'])
    for answer in data:
        writer.writerow([answer.created.date(), answer.status, answer.name, answer.address, answer.age, answer.gender, answer.notification, answer.email, answer.question1, answer.question2, answer.question3, answer.question4.all(), answer.question5.all(), answer.question6.all(), answer.question7, answer.question8, answer.question9, answer.question10, answer.question11, answer.question12, answer.question13, answer.question14, answer.question15])
    return response

@staff_member_required
def tableView(request):
    return render(request, 'anke/table.html')


def successView(request):
    return render(request, 'anke/gift.html')

anke/templates/anke/gift.html
{% extends 'base.html' %}
{% load static %}
{% block title %}久留米DMOアンケート 回答完了{% endblock %}
{% block content %}
<div class="container text-center my-4">
    <p class="my-3">アンケートへのご回答<br>ありがとうございました。<br><br><span class="text-info lead">完了通知のメール</span>をご確認ください。<br><br>JR田主丸駅構内のカフェ「カパテリア」で<br>「400円分サービス」させていただきます。<br>（スタッフにメールをお見せください。）</p>
    <a class="btn btn-primary my-3" href="{% url 'anke:index' %}">ホーム画面へ</a>
</div>
{% endblock content %}

anke/templates/anke/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}久留米ＤＭＯアンケートサイト{% endblock %}
{% block content %}
<div class="container my-3">
    <h2 class="text-warning"><i class="fas fa-poll-h"></i>&nbsp;久留米ＤＭＯ<br>&nbsp;アンケートサイト</h2>
    <div class="row my-3">
        <a class="col" href="{% url 'anke:anke' %}"><button type="button" class="btn btn-primary my-2 text-white" >回答はこちら&nbsp;<i class="far fa-hand-point-left lead"></i></button></a>
    </div>
    <img src="{% static 'anke/img/281381-01.jpg' %}" class="img-fluid" width=500rem height=auto alt="" style="border-radius: 2%;box-shadow: 1px 1px 5px 5px rgba(0, 0, 0, 0.2);">
</div>
{% endblock content %}

anke/templates/anke/list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}アンケートリスト{% endblock %}

{% block content %}
<div class="container">
<h3 class="mt-3 text-warning">アンケート回答リスト</h3>
    <div class="questions">
      <h5>☆質問リスト</h5>
      <ul  style="list-style: none;">
        <li>質問１：訪問回数</li>
        <li>質問２：比較した場所</li>
        <li>質問３：移動手段</li>
        <li>質問４：同行者(複数選択可)</li>
        <li>質問５：主目的(複数選択可)</li>
        <li>質問６：閲覧媒体(複数選択可)</li>
        <li>質問７：次の訪問予定地</li>
        <li>質問８：食事の費用</li>
        <li>質問９：買い物の額</li>
        <li>質問１０：一番好きなところ</li>
        <li>質問１１：来訪理由</li>
        <li>質問１２：ベスト旅行地</li>
        <li>質問１３：このエリアの点数</li>
        <li>質問１４：点数の理由</li>
        <li>質問１５：欠けてるもの</li>
      </ul>
    </div>
    <a class="btn btn-primary mb-3" href="{%  url 'anke:export' %}">ダウンロード</a>
    <table class="table table-sm table-striped table-responsive table-bordered">
        <thead class="table-success">
            <tr>
            <th scope="col">回答日</th>
            <th scope="col">手段</th>
            <th scope="col">氏名</th>
            <th scope="col">店舗</th>
            <th scope="col">性別</th>
            <th scope="col">年代</th>
            <th scope="col">住所</th>
            <th scope="col">Eメールアドレス</th>
            <th scope="col">メルマガ</th>
            <th scope="col">質問１</th>
            <th scope="col">質問２</th>
            <th scope="col">質問３</th>
            <th scope="col">質問４</th>
            <th scope="col">質問５</th>
            <th scope="col">質問６</th>
            <th scope="col">質問７</th>
            <th scope="col">質問８</th>
            <th scope="col">質問９</th>
            <th scope="col">質問１０</th>
            <th scope="col">質問１１</th>
            <th scope="col">質問１２</th>
            <th scope="col">質問１３</th>
            <th scope="col">質問１４</th>
            <th scope="col">質問１５</th>
            </tr>
          </thead>
    <tbody>
    {% for answer in data %}
    <tr　scope="row">
      <td>{{answer.created|date}}</td>
      <td>{{answer.get_status_display}}</td>
      <td>{{answer.name}}</td>
      <td>{{answer.get_shop_display}}</td>
      <td>{{answer.get_gender_display}}</td>
      <td>{{answer.get_age_display}}</td>
      <td>{{answer.address}}</td>
      <td>{{answer.email}}</td>
      <td>{{answer.notification}}</td>
      <td>{{answer.get_question1_display}}</td>
      <td>{{answer.question2}}</td>
      <td>{{answer.question3}}</td>
      <td>{% for friend in answer.question4.all %}
        「{{friend.name}}」
        {% endfor %}
      </td>
      <td>{% for purpose in answer.question5.all %}
        「{{purpose.name}}」
        {% endfor %}
      </td>
      <td>{% for media in answer.question6.all %}
        「{{media.name}}」
        {% endfor %}
      </td>
      <td>{{answer.question7}}</td>
      <td>{{answer.get_question8_display}}</td>
      <td>{{answer.get_question9_display}}</td>
      <td>{{answer.question10}}</td>
      <td>{{answer.question11}}</td>
      <td>{{answer.question12}}</td>
      <td>{{answer.question13}}</td>
      <td>{{answer.question14}}</td>
      <td>{{answer.question15}}</td>
  </tr>
    {% endfor %}
    </tbody>
    </table>
</div>
{% endblock content %}

anke/templates/anke/survey.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}久留米DMOアンケート{% endblock %}

{% block content %}
<div class="container">
<h2 class="mt-3 text-warning">観光調査アンケート</h2>
  <p class="mt-3">*印の質問は必須項目です。<br>&nbsp;その他は空欄でも結構です。</p>
  <form  method="post" class="mb-3">
    {% csrf_token %}
    {{ form|crispy }}
    <h6 class="mb-3">※「回答する」ボタンを押すと<br><span class="text-primary lead">通知のメール</span>が届きますので<br>ご確認ください。</h6>
    <button class="btn btn-warning" type="submit">回答する</button>
  </form>
</div>
{% endblock content %}

anke/templates/anke/table.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}アンケートリスト{% endblock %}

{% block content %}
<div class="container">
<h3 class="my-3 text-warning">管理者向け資料</h3>
<div class="row">
<a class="btn btn-warning m-2 col-sm" href="{% url 'admin:index' %}">総合管理画面</a>
<a class="btn btn-warning m-2 col-sm" href="{%  url 'anke:list' %}">久留米ＤＭＯ</a>
</div>
</div>
{% endblock content %}