anke/urls.py
from django.urls import path
from anke import views

app_name='anke'
urlpatterns = [
    path('', views.index, name='index'),
    path('anke/', views.ankeView, name='anke'),
    path('list/', views.ankeList, name='list'),
    path('export/', views.ankeExport, name='export'),
    path('table/', views.tableView, name='table'),
    path('success/', views.successView, name='success'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anke.urls')),
      # User management
    path('accounts/', include('allauth.urls')), # new
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Hachi+Maru+Pop&family=Kosugi+Maru&display=swap');
    </style>
  </head>
  <body style="font-family: 'Kosugi Maru', sans-serif;">
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <a class="navbar-brand" href="{% url 'anke:index' %}">久留米ＤＭＯ</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'anke:index' %}">ホーム<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link active" href="{% url 'anke:anke' %}">アンケート</a>
                <a class="nav-item nav-link active" href="https://www.facebook.com/kurumedmo/" target="_blank"><i class="fab fa-facebook mr-1"></i>Facebook</a>
                <a class="nav-item nav-link active" href="https://www.instagram.com/kurumedmo/" target="_blank"><i class="fab fa-instagram mr-1"></i>Instagram</a>
                <a class="nav-item nav-link active" href="https://kapateria.com/" target="_blank"><i class="fas fa-store mr-1"></i></i>Kapateria</a>
                <a class="nav-item nav-link active" href="{% url 'anke:table' %}">管理者向け</a>
                {% if user.is_staff %}
                <a class="nav-item nav-link active" href="{% url 'account_logout' %}">ログアウト</a>
                {% endif %} 
              </div>
            </div>
          </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>